name: CI

on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish win-x64
        run: dotnet.exe publish LeagueConvert.CommandLine -c Release -r win-x64 --no-self-contained -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true

      - name: Upload win-x64 build artifact
        uses: actions/upload-artifact@v3
        with:
          name: LeagueConvert.CommandLine-${{ env.name }}-win-x64
          path: LeagueConvert.CommandLine/bin/Release/net7.0/win-x64/publish
